MAX_TURN = 20

#dialogue status
DIALOGUE_STATUS_FAILED = 0
DIALOGUE_STATUS_SUCCESS = 1
DIALOGUE_STATUS_INFORM_RIGHT_SYMPTOM = 3
DIALOGUE_STATUS_INFORM_WRONG_DISEASE = 2
DIALOGUE_STATUS_REACH_MAX_TURN = -3
DIALOGUE_STATUS_COMMING = 4

#dialogue special action
ACTION_DIAGNOSE = 1

