MAX_TURN = 20

#dialogue status
DIALOGUE_STATUS_FAILED = 0
DIALOGUE_STATUS_SUCCESS = 1
DIALOGUE_STATUS_TOP3 = 6
DIALOGUE_STATUS_TOP5 = 7
DIALOGUE_STATUS_INFORM_RIGHT_SYMPTOM = 3
DIALOGUE_STATUS_INFORM_WRONG_DISEASE = 2
DIALOGUE_STATUS_REACH_MAX_TURN = -3
DIALOGUE_STATUS_COMMING = 4
DIALOGUE_STATUS_NOT_COME_YET = 5
#dialogue special action
ACTION_DIAGNOSE = 1
CLOSE_DIALOGUE = "closing"
THANKS = "thanks"


I_DO_NOT_CARE = "I don't care."
I_DO_NOT_KNOW = "I don't know."
I_DENY = "No"


#lower-agent


VALUE_UNKNOWN = "UNK"
